// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiulEjAI18Gt3KhEq0y_LwSlBYHbEZPuM',
    appId: '1:974585428824:web:9a3415508c58450251c32d',
    messagingSenderId: '974585428824',
    projectId: 'goipvc-47944',
    authDomain: 'goipvc-47944.firebaseapp.com',
    storageBucket: 'goipvc-47944.firebasestorage.app',
    measurementId: 'G-D69NZV87KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHCSM6RexwW7BwfqaXP83k9TH66iXQT2U',
    appId: '1:974585428824:android:68e6e0c99633545651c32d',
    messagingSenderId: '974585428824',
    projectId: 'goipvc-47944',
    storageBucket: 'goipvc-47944.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5JRJQvjDdbwTf1zY_2Pd6WljKL7jPqo',
    appId: '1:974585428824:ios:66e8a48b1e8a399a51c32d',
    messagingSenderId: '974585428824',
    projectId: 'goipvc-47944',
    storageBucket: 'goipvc-47944.firebasestorage.app',
    iosBundleId: 'app.goipvc',
  );
}
